### ISSUE TITLE
probable bug in AI minmax code

### ISSUE THREAD

**Issue by barrybecker4** [krajzeg/compact-conflict#2]
@krajzeg, I noticed what is probably a bug on this line:

`var better = (!node.b) || (maximizingNode && (child.v > node.v)) || ((!maximizingNode) && (child.v < node));`

I think it should be

`var better = (!node.b) || (maximizingNode && (child.v > node.v)) || ((!maximizingNode) && (child.v < node.v));`

**Comment by krajzeg** [comment]
Woah! That's definitely a bug, and a serious one at that. One wishes Javascript would be a little more strict with its operators. 

It's been a *while* since I did anything with this project and I'm pretty busy nowadays, but I'll fix it when I have a little bit of time to test it. I really wonder how the AI in the game still managed to work in a reasonable fashion with half of its min-max algorithm basically disabled (since child.v < node will always be false).

Good catch!

**Comment by krajzeg** [comment]
Fixed it on master, since it was so obviously wrong. It'll take me a while to release the fixed version though, since I no longer have the machine originally used to write this, so I don't have the minifier/build tools required by the build scripts at hand.

**Comment by barrybecker4** [comment]
I've been enjoying the game and have been making [some modifications in my fork](https://github.com/barrybecker4/world-conflict). After refactoring it a bit for maintainability instead of compactness, I hope to make an online version so that lots of games can happen simultaneously and players of the same game do not have to be sitting at the same computer. Here are my [thoughts](https://github.com/barrybecker4/world-conflict/issues/5) on how to do it.

**Comment by krajzeg** [comment]
Have fun with the project! Once you're done, do let me know so we can play a round :)
